### ISSUE TITLE
PAYENGARCHE-1: Unable to create project from custom archetype

### ISSUE THREAD

**Issue by payengineer** [rs-software-engineering/payengineer-webui-customer-archetype#1]
## Issue Overview

- Use custom archetype 'payengineer-custom-web-ui-archetype-1.0.00.00' to create new WEB UI project for Lilatexshop customer.
- In Eclipse IDE choose 'Create a Maven project' and select custom archetype 'payengineer-custom-web-ui-archetype-1.0.00.00' as template project
- Exception dialog window will pop up with detail message saying "Unable to create project from archetype ..."

## Issue Message Generated
Unable to create project from archetype [com.payengineer.webui:payengineer-custom-web-ui-archetype:1.0.00.00 -> <remote_or_local_repository_location>]
Error merging velocity templates

### Exception Stack Trace

org.apache.maven.archetype.old.ArchetypeTemplateProcessingException: Error merging velocity templates
	at org.apache.maven.archetype.old.DefaultOldArchetype.processTemplate(DefaultOldArchetype.java:858)
	at org.apache.maven.archetype.old.DefaultOldArchetype.processTemplate(DefaultOldArchetype.java:718)
	at org.apache.maven.archetype.old.DefaultOldArchetype.processResources(DefaultOldArchetype.java:759)
	at org.apache.maven.archetype.old.DefaultOldArchetype.processTemplates(DefaultOldArchetype.java:675)
	at org.apache.maven.archetype.old.DefaultOldArchetype.createArchetype(DefaultOldArchetype.java:330)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.processOldArchetype(DefaultArchetypeGenerator.java:135)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:104)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:143)
	at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:169)
	at org.apache.maven.archetype.DefaultArchetypeManager.generateProjectFromArchetype(DefaultArchetypeManager.java:73)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:844)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:792)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1374)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:790)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizard$5.doCreateMavenProjects(MavenProjectWizard.java:241)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectJob$1.doCreateMavenProjects(AbstractCreateMavenProjectJob.java:63)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:73)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectJob.runInWorkspace(AbstractCreateMavenProjectJob.java:67)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'archetype-resources/src/main/resources/html/index.html'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:452)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:335)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1102)
	at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:498)
	at org.apache.maven.archetype.old.DefaultOldArchetype.processTemplate(DefaultOldArchetype.java:848)
	... 23 more

**Comment by payengineer** [comment]
This issue is resolved now.

## Issue Resolution
The cause of the issue was the structure of the archetype-resource folder
### Old Folder Structure

```bash
+---archetype-resources
|   |   pom.xml
|   |   
|   \---src
|       +---main
|       |   +---java
|       |   |       DummyClass.java
|       |               
|       \---test
|           \---java
|                   DummyClassTest.java
|                   
+---css
+---fonts
+---html
+---js
\---META-INF
    \---maven
            archetype.xml
```

### New Folder Structure
```bash
+---archetype-resources
|   |   pom.xml
|   |   
|   \---src
|       +---main
|       |   +---java
|       |   |       DummyClass.java
|       |   |       
|       |   \---resources
|       |       +---css
|       |       |       dummy.css
|       |       |       
|       |       +---fonts
|       |       |       dummy.svg
|       |       |       
|       |       +---html
|       |       |       dummy.html
|       |       |       
|       |       \---js
|       |               dummy.js
|       |               
|       \---test
|           \---java
|                   DummyClassTest.java
|                   
+---css
+---fonts
+---html
+---js
\---META-INF
    \---maven
            archetype.xml
```
## Git Commit
4e6acde84dc799e7cacaec3ed056c3a84f246ebf

After this change you can use project template to generate basic web ui structure for simple web site front-end development.

Kind regards,
Nikola Bikic
